/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.jtattoo.plaf.AbstractLookAndFeel;
import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.luna.LunaLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import com.jtattoo.plaf.smart.SmartLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.SimpleFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.multi.MultiLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.plaf.synth.SynthLookAndFeel;
import product.DataProduct;
import transaksi.TransaksiForm;

/**
 *
 * @author gusty_g.n.m
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        super("Main Form");
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.showDate();
        this.showTime();
    }

//    private void initComponents() {
//        setPreferredSize(new Dimension(400, 200));
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        pack();
//        setVisible(true);
//    }
    public void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEE, d MMM yyyy");
        lblDate.setText(s.format(d));
    }

    public void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(s.format(d));
            }
        }).start();
    }

    public void logOut() {
        main.MainForm.mnLogin.setEnabled(true);
        main.MainForm.btnLogin.setEnabled(true);
        main.MainForm.mnMenu.setEnabled(false);
        main.MainForm.mnLogout.setEnabled(false);
        main.MainForm.btnLogout.setEnabled(false);
        main.MainForm.btnDataProduct.setEnabled(false);
        main.MainForm.btnTransaksi.setEnabled(false);
        main.MainForm.btnPendapatan.setEnabled(false);
        main.MainForm.btnRiwayat.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        btnLogout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnAbout = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        btnDataProduct = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnPendapatan = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        jMenuPengembalian = new javax.swing.JMenuBar();
        mnAkses = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        mnMenu = new javax.swing.JMenu();
        mnDataProduct = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenuItem();
        mnPendapatan = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Penyewaan Multimedia");

        jToolBar1.setBackground(new java.awt.Color(0, 102, 153));
        jToolBar1.setRollover(true);

        btnLogin.setBackground(new java.awt.Color(0, 102, 153));
        btnLogin.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Login-icon.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Klik untuk login");
        btnLogin.setEnabled(false);
        btnLogin.setFocusable(false);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogin);
        jToolBar1.add(jSeparator1);

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jToolBar1.add(jSeparator14);

        btnLogout.setBackground(new java.awt.Color(0, 102, 153));
        btnLogout.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Logout-icon.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("Klik untuk logout");
        btnLogout.setEnabled(false);
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);
        jToolBar1.add(jSeparator2);

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jToolBar1.add(jSeparator12);

        btnAbout.setBackground(new java.awt.Color(0, 102, 153));
        btnAbout.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Contact-icon.png"))); // NOI18N
        btnAbout.setText("About");
        btnAbout.setToolTipText("Tentang Aplikasi Ini");
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbout);

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jToolBar1.add(jSeparator5);

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jToolBar1.add(jSeparator8);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        lblJudul.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TITLE.png"))); // NOI18N
        lblJudul.setLabelFor(this);
        lblJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblJudul.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date");

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Time");

        lblDate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate1.setForeground(new java.awt.Color(255, 255, 255));
        lblDate1.setText("||");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(613, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 709, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(lblDate)
                    .addComponent(lblDate1))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(lblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGap(160, 160, 160)))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        btnKeluar.setBackground(new java.awt.Color(204, 0, 0));
        btnKeluar.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Actions-dialog-close-icon (2).png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setToolTipText("Klik untuk keluar dari program");
        btnKeluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKeluar.setFocusable(false);
        btnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnDataProduct.setBackground(new java.awt.Color(0, 153, 0));
        btnDataProduct.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        btnDataProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Surveys-icon.png"))); // NOI18N
        btnDataProduct.setText("Data Product");
        btnDataProduct.setToolTipText("Klik untuk menambahkan data product");
        btnDataProduct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDataProduct.setFocusable(false);
        btnDataProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDataProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataProductActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(0, 102, 153));
        btnTransaksi.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Fax-icon (2).png"))); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setToolTipText("Klik untuk melakukan transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransaksi.setFocusable(false);
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnPendapatan.setBackground(new java.awt.Color(0, 153, 153));
        btnPendapatan.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        btnPendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Cash-register-icon (2).png"))); // NOI18N
        btnPendapatan.setText("Pendapatan");
        btnPendapatan.setToolTipText("Klik untuk melihat pendapatan");
        btnPendapatan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPendapatan.setFocusable(false);
        btnPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPendapatan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatanActionPerformed(evt);
            }
        });

        btnRiwayat.setBackground(new java.awt.Color(153, 0, 204));
        btnRiwayat.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        btnRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Actions-edit-clear-history-icon (1).png"))); // NOI18N
        btnRiwayat.setText("Riwayat");
        btnRiwayat.setToolTipText("Klik untuk melihat Riwayat/HIstory");
        btnRiwayat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRiwayat.setFocusable(false);
        btnRiwayat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRiwayat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDataProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDataProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mnAkses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img/win.png"))); // NOI18N
        mnAkses.setText("Akses ");
        mnAkses.setEnabled(false);
        mnAkses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAksesMouseClicked(evt);
            }
        });
        mnAkses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAksesActionPerformed(evt);
            }
        });

        mnLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Login-icon (1).png"))); // NOI18N
        mnLogin.setText("Login");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });
        mnAkses.add(mnLogin);

        mnLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Logout-icon (1).png"))); // NOI18N
        mnLogout.setText("Logout");
        mnLogout.setEnabled(false);
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnAkses.add(mnLogout);

        mnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Actions-dialog-close-icon.png"))); // NOI18N
        mnExit.setText("Keluar");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnAkses.add(mnExit);

        jMenuPengembalian.add(mnAkses);

        mnMenu.setText("Menu ");
        mnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMenuMouseClicked(evt);
            }
        });

        mnDataProduct.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnDataProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Surveys-icon (1).png"))); // NOI18N
        mnDataProduct.setText("Data Product");
        mnDataProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDataProductActionPerformed(evt);
            }
        });
        mnMenu.add(mnDataProduct);

        mnTransaksi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Fax-icon (1).png"))); // NOI18N
        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        mnMenu.add(mnTransaksi);

        mnPendapatan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnPendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/Cash-register-icon.png"))); // NOI18N
        mnPendapatan.setText("Pendapatan");
        mnPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPendapatanActionPerformed(evt);
            }
        });
        mnMenu.add(mnPendapatan);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/history.png"))); // NOI18N
        jMenuItem1.setText("Riwayat");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnMenu.add(jMenuItem1);

        jMenuPengembalian.add(mnMenu);

        mnAbout.setText("About");
        mnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAboutMouseClicked(evt);
            }
        });
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenuPengembalian.add(mnAbout);

        setJMenuBar(jMenuPengembalian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAksesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAksesMouseClicked
//        this.setVisible(false);
//        new Akun.LoginForm().setVisible(true);
    }//GEN-LAST:event_mnAksesMouseClicked

    private void mnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMenuMouseClicked

    }//GEN-LAST:event_mnMenuMouseClicked

    private void mnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAboutMouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_mnAboutMouseClicked

    private void mnAksesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAksesActionPerformed

    }//GEN-LAST:event_mnAksesActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed

    }//GEN-LAST:event_mnAboutActionPerformed

    private void mnDataProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDataProductActionPerformed
        product.ProductForm p = new product.ProductForm();
        p.setVisible(true);
    }//GEN-LAST:event_mnDataProductActionPerformed

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        new akun.LoginForm().setVisible(true);
        new akun.LoginForm().btnRegistrasi.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_mnLoginActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "Anda akan logout?", "konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            logOut();
            new akun.LoginForm().setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "Anda yakin ingin keluar?", "konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        new transaksi.TransaksiForm().setVisible(true);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "Anda akan logout?", "konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            logOut();
            new akun.LoginForm().setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new akun.LoginForm().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnDataProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProductActionPerformed
        product.ProductForm p = new product.ProductForm();
        p.setVisible(true);
    }//GEN-LAST:event_btnDataProductActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        new transaksi.TransaksiForm().setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "Anda yakin ingin keluar?", "konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void mnPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPendapatanActionPerformed
        new pendapatan.PendapatanForm().setVisible(true);
    }//GEN-LAST:event_mnPendapatanActionPerformed

    private void btnPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatanActionPerformed
        new pendapatan.PendapatanForm().setVisible(true);
    }//GEN-LAST:event_btnPendapatanActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        new riwayat.RiwayatForm().setVisible(true);
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new riwayat.RiwayatForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.alumunium.AlumuniumLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new MainForm());
        } catch (Exception e) {

        }
        UIManager.setLookAndFeel(new WindowsLookAndFeel());
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAbout;
    public static javax.swing.JButton btnDataProduct;
    public static javax.swing.JButton btnKeluar;
    public static javax.swing.JButton btnLogin;
    public static javax.swing.JButton btnLogout;
    public static javax.swing.JButton btnPendapatan;
    public static javax.swing.JButton btnRiwayat;
    public static javax.swing.JButton btnTransaksi;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar jMenuPengembalian;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTime;
    public static javax.swing.JMenu mnAbout;
    public static javax.swing.JMenu mnAkses;
    private javax.swing.JMenuItem mnDataProduct;
    private javax.swing.JMenuItem mnExit;
    public static javax.swing.JMenuItem mnLogin;
    public static javax.swing.JMenuItem mnLogout;
    public static javax.swing.JMenu mnMenu;
    private javax.swing.JMenuItem mnPendapatan;
    private javax.swing.JMenuItem mnTransaksi;
    // End of variables declaration//GEN-END:variables
}
